apiVersion: apps/v1
kind: Deployment
metadata:
  name: snappass-dep
  labels:
    app: snappass
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: snappass
  template:
    metadata:
      labels:
        app: snappass
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: redis
          image: harbor.e2x.com/library/snappass:0.0.1
        - name: snappass
          image: redis:5.0.5-alpine
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: NO_SSL
              value: "true"