apiVersion: v1
kind: Service
metadata:
  name: snappass-svc
  namespace: snappass-ns
  labels:
    app: snappass
spec:
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort
  selector:
    app: snappass